version: '2'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    volumes:
      - .:/srv
    depends_on:
      - redis
  redis:
    image: redis
